[package]
name = "calc-sql"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.9.3"
derive_more = { version = "1.0.0", features = ["full"] }
enum-as-inner = "0.6.0"

[dev-dependencies]
ariadne = "0.4.1"
dir-test = "0.3.0"
inquire = "0.7.5"
spreadsheet-ods = "0.22.5"
